import { useEffect, useState } from "react";
import type { FC, ReactNode } from "react";
import { ShieldCheckIcon, SparklesIcon, ImagePlusIcon, TriangleAlertIcon } from "./Icons";
import type { ForensicFinalResult, ForensicCrossCheck, ImageDimensions, V5DResult } from "../types";

interface ForensicVerdictProps {
  finalResult: ForensicFinalResult;
  v5_d?: V5DResult;
  crossCheck?: ForensicCrossCheck;
  primaryVerdict?: string;
  primaryConfidence?: number;
  filename?: string;
  dimensions?: ImageDimensions | null;
}

interface VerdictConfig {
  label: string;
  themeClass: string;
  accentColor: string;
  badgeBg: string;
  icon: ReactNode;
  explanation: string;
}

export const ForensicVerdict: FC<ForensicVerdictProps> = ({
  finalResult,
  v5_d,
  crossCheck,
  primaryVerdict,
  primaryConfidence,
  filename = "Specimen",
  dimensions,
}) => {
  const [animatedProgress, setAnimatedProgress] = useState(0);

  const hasV5D = Boolean(v5_d && !v5_d.error);
  const activeVerdict = (primaryVerdict ?? v5_d?.prediction ?? (finalResult.label === "AI_GENERATED" ? "AI-GENERATED" : finalResult.label === "REAL_ORIGINAL" ? "REAL" : finalResult.label));
  const isV5DPrimary = hasV5D;

  // Confidence calculations
  const rawConf = isV5DPrimary
    ? (primaryConfidence ?? v5_d!.confidence)
    : (finalResult.confidence <= 1.0 ? finalResult.confidence * 100 : finalResult.confidence);

  const confDisplay = rawConf.toFixed(1);

  const isUncertain = !isV5DPrimary && finalResult.label === "UNCERTAIN";
  const isDomainAbstention = !isV5DPrimary && finalResult.decision_source === "domain_risk_abstention";
  const isGenuineConsensus = !isV5DPrimary && finalResult.decision_source === "genuine_photograph_consensus";
  const isConsensusOverride = !isV5DPrimary && finalResult.decision_source === "generation_consensus_override";

  const targetPercent = isUncertain ? 0 : Math.min(100, Math.max(0, rawConf));

  useEffect(() => {
    // Smooth progress animation on mount
    const timer = setTimeout(() => {
      setAnimatedProgress(targetPercent);
    }, 60);
    return () => clearTimeout(timer);
  }, [targetPercent]);

  const getVerdictConfig = (): VerdictConfig => {
    if (isV5DPrimary) {
      if (activeVerdict === "AI-GENERATED" || activeVerdict === "AI_GENERATED") {
        return {
          label: "AI GENERATED",
          themeClass: "verdict-state-ai",
          accentColor: "#E11D48",
          badgeBg: "rgba(225, 29, 72, 0.08)",
          icon: <SparklesIcon size={26} />,
          explanation: "Classified as AI GENERATED by primary model V5-D Gated Residual ResNet-50 via triple-stream feature fusion (spatial, frequency, and noise residual).",
        };
      }
      return {
        label: "REAL ORIGINAL",
        themeClass: "verdict-state-real",
        accentColor: "#059669",
        badgeBg: "rgba(5, 150, 105, 0.08)",
        icon: <ShieldCheckIcon size={26} />,
        explanation: "Classified as REAL ORIGINAL by primary model V5-D Gated Residual ResNet-50 via triple-stream feature fusion (spatial, frequency, and noise residual).",
      };
    }

    // Fallback: Legacy Strategy E
    switch (finalResult.label) {
      case "REAL_ORIGINAL":
        return {
          label: "REAL ORIGINAL",
          themeClass: "verdict-state-real",
          accentColor: "#059669",
          badgeBg: "rgba(5, 150, 105, 0.08)",
          icon: <ShieldCheckIcon size={26} />,
          explanation: "Classified as REAL ORIGINAL based on current forensic signals.",
        };
      case "AI_GENERATED":
        return {
          label: "AI GENERATED",
          themeClass: "verdict-state-ai",
          accentColor: "#E11D48",
          badgeBg: "rgba(225, 29, 72, 0.08)",
          icon: <SparklesIcon size={26} />,
          explanation: "Classified as AI GENERATED based on current forensic signals.",
        };
      case "AI_MANIPULATED":
        return {
          label: "AI MANIPULATED",
          themeClass: "verdict-state-manip",
          accentColor: "#6C63D9",
          badgeBg: "rgba(108, 99, 217, 0.08)",
          icon: <ImagePlusIcon size={26} />,
          explanation: "Classified as AI MANIPULATED based on current forensic signals.",
        };
      case "UNCERTAIN":
      default:
        return {
          label: "UNCERTAIN",
          themeClass: "verdict-state-uncertain",
          accentColor: "#D97706",
          badgeBg: "rgba(217, 119, 6, 0.08)",
          icon: <TriangleAlertIcon size={26} />,
          explanation: "The available forensic signals do not provide a sufficiently clear classification.",
        };
    }
  };

  const config = getVerdictConfig();

  // SVG Circular Confidence Orbit geometry
  const radius = 56;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (animatedProgress / 100) * circumference;

  return (
    <div className={`evidence-passport-card ${config.themeClass}`}>
      {/* Passport Header Ribbon */}
      <div className="passport-header-ribbon">
        <div className="passport-title-group">
          <span className="passport-kicker font-mono">DIGITAL EVIDENCE PASSPORT</span>
          <span className="passport-seal-tag font-mono">
            {isV5DPrimary ? "V5-D PRIMARY • CALIBRATED" : "AUTHENTICITY RECORD"}
          </span>
        </div>
        <div className="passport-id-badge font-mono">
          SEC-ID: #EV-{(rawConf * 13).toFixed(0).padStart(4, "0")}
        </div>
      </div>

      {/* Main Forensic Verdict Banner */}
      <div className="verdict-banner-container">
        <div className="verdict-tag-header">
          <span className="verdict-caption font-mono">
            {isV5DPrimary ? "PRIMARY CLASSIFIER VERDICT (V5-D)" : "FORENSIC VERDICT"}
          </span>
        </div>

        <div className="verdict-badge-row">
          <div 
            className="verdict-icon-container" 
            style={{ color: config.accentColor, backgroundColor: config.badgeBg }}
          >
            {config.icon}
          </div>
          <div className="verdict-title-wrap">
            <h2 className="verdict-primary-title" style={{ color: config.accentColor }}>
              {config.label}
            </h2>
          </div>
        </div>

        {/* Official Verdict Explanation */}
        <p className="verdict-formal-explanation">
          {isV5DPrimary ? config.explanation : (finalResult.reason || config.explanation)}
        </p>

        {/* Supporting Forensic Cross-Check Callout */}
        {crossCheck && (
          <div
            style={{
              marginTop: "14px",
              padding: "10px 14px",
              borderRadius: "8px",
              backgroundColor: crossCheck.status === "CONSISTENT" ? "rgba(5, 150, 105, 0.06)" : "rgba(217, 119, 6, 0.08)",
              border: `1px solid ${crossCheck.status === "CONSISTENT" ? "rgba(5, 150, 105, 0.25)" : "rgba(217, 119, 6, 0.3)"}`,
              display: "flex",
              flexDirection: "column",
              gap: "4px",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "6px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                <span
                  className="font-mono"
                  style={{
                    fontSize: "10px",
                    fontWeight: 700,
                    letterSpacing: "0.06em",
                    color: crossCheck.status === "CONSISTENT" ? "#059669" : "#D97706",
                  }}
                >
                  FORENSIC CROSS-CHECK:
                </span>
                <span
                  className="font-mono"
                  style={{
                    fontSize: "9.5px",
                    fontWeight: 800,
                    padding: "2px 6px",
                    borderRadius: "4px",
                    backgroundColor: crossCheck.status === "CONSISTENT" ? "rgba(5, 150, 105, 0.12)" : "rgba(217, 119, 6, 0.15)",
                    color: crossCheck.status === "CONSISTENT" ? "#059669" : "#B45309",
                  }}
                >
                  {crossCheck.status === "CONSISTENT" ? "✓ CONSISTENT" : "⚠ DIVERGENT / ABSTAINED"}
                </span>
              </div>
              {crossCheck.strategy_e_verdict && (
                <span className="font-mono" style={{ fontSize: "9.5px", color: "var(--text-secondary)" }}>
                  Strategy E: <strong>{crossCheck.strategy_e_verdict}</strong>
                  {crossCheck.strategy_e_confidence !== undefined && ` (${crossCheck.strategy_e_confidence}%)`}
                </span>
              )}
            </div>
            <p style={{ margin: 0, fontSize: "11.5px", color: "var(--text-secondary)", lineHeight: 1.4 }}>
              {crossCheck.explanation}
            </p>
          </div>
        )}
      </div>

      {/* Confidence Orbit Section */}
      <div className="confidence-orbit-section">
        <div className="orbit-interactive-cluster">
          <div className="orbit-svg-wrapper">
            <svg className="confidence-orbit-svg" width="144" height="144" viewBox="0 0 144 144">
              {/* Outer Decorative Orbit Ring */}
              <circle
                className="orbit-outer-dash"
                cx="72"
                cy="72"
                r="68"
                strokeWidth="1"
                strokeDasharray="4 6"
              />
              {/* Background Track */}
              <circle
                className="orbit-bg-track"
                cx="72"
                cy="72"
                r={radius}
                strokeWidth="7"
              />
              {/* Foreground Animated Confidence Orbit Arc */}
              <circle
                className="orbit-active-arc"
                cx="72"
                cy="72"
                r={radius}
                strokeWidth="7"
                strokeDasharray={circumference}
                strokeDashoffset={strokeDashoffset}
                strokeLinecap="round"
                transform="rotate(-90 72 72)"
                style={{ stroke: config.accentColor }}
              />
            </svg>

            {/* Orbit Center Readout */}
            <div className="orbit-center-display">
              {isUncertain ? (
                <>
                  <span className="orbit-metric-value font-mono" style={{ color: config.accentColor, fontSize: "1.1rem", letterSpacing: "0.04em" }}>
                    INCONCLUSIVE
                  </span>
                  <span className="orbit-metric-label font-mono">
                    {finalResult.reliability_state ? `RELIABILITY: ${finalResult.reliability_state}` : "RELIABILITY: LOW"}
                  </span>
                </>
              ) : (
                <>
                  <span className="orbit-metric-value font-mono" style={{ color: config.accentColor }}>
                    {confDisplay}%
                  </span>
                  <span className="orbit-metric-label font-mono">
                    {isV5DPrimary ? "CALIBRATED CONFIDENCE" : isGenuineConsensus ? "ORIGINALITY EVIDENCE" : isConsensusOverride ? "CONSENSUS EVIDENCE" : "CONFIDENCE"}
                  </span>
                </>
              )}
            </div>
          </div>

          <div className="orbit-clarification-text">
            <span className="orbit-heading font-mono">
              {isV5DPrimary
                ? "V5-D POST-HOC CALIBRATION (T=2.20)"
                : isDomainAbstention
                ? "DOMAIN RISK ABSTENTION"
                : isUncertain
                ? "RELIABILITY ABSTENTION"
                : isGenuineConsensus
                ? "ORIGINALITY EVIDENCE"
                : isConsensusOverride
                ? "CONSENSUS EVIDENCE"
                : "CONFIDENCE CALIBRATION"}
            </span>
            <p className="orbit-desc">
              {isV5DPrimary
                ? "Confidence calibrated via Temperature Scaling (T = 2.20, ECE reduced from 1.97% to 0.47%). Primary classification integrates spatial, frequency, and noise residual domain streams."
                : isDomainAbstention
                ? "Image exhibits document-like visual characteristics outside the validated natural-photograph operating distribution."
                : isUncertain
                ? "Forensic signals are conflicting or out-of-domain. The system refrains from forcing an uncalibrated verdict."
                : isGenuineConsensus
                ? "High originality evidence from the localized manipulation analysis."
                : isConsensusOverride
                ? "Spatial and frequency models independently identified synthetic evidence outside Strategy E calibration."
                : "Posterior confidence calibrated across whole-image synthesis and localized manipulation boundaries."}
            </p>
          </div>
        </div>
      </div>

      {/* Evidence Passport Details Identity Section */}
      <div className="passport-identity-grid font-mono">
        <div className="passport-field-cell">
          <span className="field-label">EVIDENCE</span>
          <span className="field-value" title={filename}>
            {filename}
            {dimensions ? ` (${dimensions.width}×${dimensions.height})` : ""}
          </span>
        </div>

        <div className="passport-field-cell">
          <span className="field-label">{isV5DPrimary ? "PRIMARY MODEL" : "STATUS"}</span>
          <span className="field-value text-semantic" style={{ color: config.accentColor }}>
            {isV5DPrimary
              ? "V5-D GATED RESIDUAL (ResNet-50)"
              : isDomainAbstention
              ? "⚠ OUT OF DOMAIN / ABSTAINED"
              : isUncertain
              ? "⚠ SIGNAL CONFLICT / ABSTAINED"
              : "● VERIFIED COMPLETE"}
          </span>
        </div>

        <div className="passport-field-cell">
          <span className="field-label">
            {isV5DPrimary
              ? "CALIBRATION"
              : isDomainAbstention
              ? "EVIDENCE"
              : isGenuineConsensus
              ? "ORIGINALITY"
              : isConsensusOverride
              ? "CONSENSUS"
              : "CONFIDENCE"}
          </span>
          <span className="field-value">
            {isV5DPrimary
              ? `TEMP SCALING (${confDisplay}%)`
              : isDomainAbstention
              ? "INCONCLUSIVE (DOMAIN SHIFT)"
              : isUncertain
              ? "INCONCLUSIVE (ABSTENTION)"
              : isGenuineConsensus
              ? `${confDisplay}% ORIGINALITY EVIDENCE`
              : isConsensusOverride
              ? `${confDisplay}% CONSENSUS EVIDENCE`
              : `${confDisplay}% CALIBRATED`}
          </span>
        </div>

        <div className="passport-field-cell">
          <span className="field-label">{isV5DPrimary ? "CROSS-CHECK" : "ANALYSIS"}</span>
          <span className="field-value">
            {isV5DPrimary
              ? crossCheck
                ? `${crossCheck.status} (${crossCheck.strategy_e_verdict || "STRATEGY E"})`
                : "INDEPENDENT"
              : isDomainAbstention
              ? "DOMAIN RELIABILITY GATE"
              : isGenuineConsensus
              ? "AUTHENTIC PHOTOGRAPH CONSENSUS"
              : isConsensusOverride
              ? "MULTI-STREAM GENERATION CONSENSUS"
              : "DUAL-STREAM SYNTHESIS"}
          </span>
        </div>
      </div>
    </div>
  );
};
